### PR TITLE
Correcting URLs, Conforming to Specification, Adding Order, and Minor Corrections

### PR DESCRIPTION
**Pull request by dillonredding**
* Including `.xml` in `href`s to correct URLs
* Removing `rt` from `semantic` `descriptor`s to conform to [section 2.2.11 of the specification](https://tools.ietf.org/html/draft-amundsen-richardson-foster-alps-03#section-2.2.11)
* Adding `Order` schema and immediate "family" (e.g., `OrderStatus`, `Invoice`, `ParcelDelivery`)
* Correcting some typos and updating some existing properties

### CODE REVIEW

**Comment by mamund** [comment]
@dillonredding 

do you need me to approve this PR on the alps org?

**Comment by dillonredding** [comment]
@mamund

No idea 😅 I was going through the ALPS registry and noticed some discrepancies, so I thought I'd contribute some fixes. I didn't see any contribution guidelines, so I decided to just make a PR and go from there. Not sure if these changes will automatically get picked up by the registry or not.

**Comment by mamund** [comment]
first, really appreciate the contribution. this was a set of scripts/docs that @leonardr put together when we were first working on ALPS and the "RESTful Web APIs" book.

your addtions/fixes are onpoint and i'll be sure to merge them in ASAP.

thanks.

BTW - @filip26 has put together a really nice alps validation/converter that i've been using regularly, too.  (https://github.com/filip26/alps)

**Comment by dillonredding** [comment]
Thank you, @mamund! I might have some more contributions soon 😁

P.S. _RESTful Web APIs_ is basically my bible when it comes to APIs. At work, I lead the team that governs and manages APIs. That book opened my eyes to what is truly REST. It's my baseline, my litmus test for how APIs should be designed and that's the direction I've been pushing for at my job. For that, I thank you!

**Comment by mamund** [comment]
thanks for the feedback.  the book is really @leonardr 's work. i assisted. 

and, please keep the contribs coming!

FWIW, originally, we planned for all the href's to be void of media type hints (.xml, .json, etc.) and wanted folks to use conneg to ask for a format they desired. but we never got that up and running. so, thanks for making these all workable. I'll be updating the live site w/ your changes sometime this week.

then i'll work on converting this set to JSON and posting them, too.

thanks again.

**Pull request merged**
