### PR TITLE
Publish a web site using GitHub pages

### PR DESCRIPTION
**Pull request by koriym**
Publish the `import` web site in https://alps-io.github.io/imports/.

Web publishing is done by GitHub actions. It will be updated manually or by cron once a week.

### CODE REVIEW

**Comment by koriym** [comment]
It's already published in Jekyll !! 
I'm going to close this PR; it would be nice if the README indicated the [URL](https://alps-io.github.io/imports/).

**Comment by koriym** [comment]
https://koriym.github.io/imports/

I'll also leave my version's URL for the record.

**Comment by dillonredding** [comment]
> It's already published in Jekyll !! I'm going to close this PR; it would be nice if the README indicated the [URL](https://alps-io.github.io/imports/).

@mamund, could you set the website URL to the GitHub pages for this repository? That requires admin access 😄

**Comment by koriym** [comment]
@dillonredding I found yours is the better. ;) GitHub action added but it helps a little.

**Comment by koriym** [comment]
@dillonredding I didn't find your script which also produces `index.html`?

**Comment by dillonredding** [comment]
@koriym
[`index.md`](https://github.com/alps-io/imports/blob/master/schema.org/index.md) is generated in [`/schema.org/src/index.ts`](https://github.com/alps-io/imports/blob/master/schema.org/src/index.ts). Jekyll takes care of converting that to HTML.

**Comment by dillonredding** [comment]
> @dillonredding I found yours is the better. ;) GitHub action added but it helps a little.

I really like the idea of a reoccurring action to keep everything up-to-date! We'll need to update the script to pull from Schema.org rather than a local copy for that to have any effect though.

**Comment by mamund** [comment]
so what is the URL that we should be using?

**Comment by koriym** [comment]
"import site" URL is https://alps-io.github.io/imports/ .

**Comment by mamund** [comment]
updated the repo's website URL to point to https://alps-io.github.com/imports/

cool?

**Comment by dillonredding** [comment]
Perfect 😁 Thanks, @mamund!

**Comment by mamund** [comment]
np.

**Comment by koriym** [comment]
https://alps-io.github.io/imports/ not  https://alps-io.github.com/imports/. But the updated URL is fine.

**Pull request closed without merging**
